name: expense_detection
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  pie_chart: ^3.1.1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
     - family: Quicksand
       fonts:
         - asset: fonts/Quicksand/static/Quicksand-Regular.ttf
         - asset: fonts/Quicksand/static/Quicksand-Bold.ttf
           weight: 700
